# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from tools import wait


class TestItmsbiletsuccess():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_itmsbiletsuccess(self):
    self.driver.get("https://www.bilet.com/")
    self.driver.set_window_size(1853, 1022)
    time.sleep(3000);
    self.driver.find_element(By.ID, "bus-origin-text-input").click()
    self.driver.find_element(By.ID, "bus-destination-text-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".tt-open .tt-suggestion:nth-child(1)").click()
    self.driver.find_element(By.ID, "bus-destination-text-input").send_keys("Ankara")
    self.driver.find_element(By.ID, "tomorrow").click()
    self.driver.find_element(By.ID, "bus-search-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ticket:nth-child(5) .btn:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".seat-plan-row:nth-child(14) > .seat-plan-seat").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gender-selector-male").click()
    self.driver.find_element(By.ID, "confbtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-brand > img").click()
  

tst = TestItmsbiletsuccess()
tst.setup_method("success")
tst.test_itmsbiletsuccess()